version: '3.8'

# Development override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Override app service for development
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Mount source code for hot reload
      - ./app:/app/app:ro
      - ./scripts:/app/scripts:ro
      - ./news_data.json:/app/news_data.json:ro
      - ./logs:/app/logs
    environment:
      # Development-specific environment variables
      DEBUG: "True"
      LOG_LEVEL: DEBUG
      RELOAD: "True"
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port

  # Development database with exposed ports
  mongodb:
    ports:
      - "27017:27017"
    environment:
      # Less secure for development
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: dev123
    volumes:
      - mongodb_dev_data:/data/db

  # Development Redis with exposed ports
  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass dev123

  # Add development tools
  mongo-express:
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev123
      ME_CONFIG_MONGODB_URL: mongodb://admin:dev123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: dev123

  redis-commander:
    environment:
      REDIS_HOSTS: local:redis:6379:0:dev123
      HTTP_USER: admin
      HTTP_PASSWORD: dev123

volumes:
  mongodb_dev_data:
    driver: local
